name: CI checks
on: push

jobs:
  back-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: docker compose -f docker-compose.ci.back-end.yml up --build --exit-code-from back-end

  web-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: docker compose -f docker-compose.ci.web-app.yml up --build --exit-code-from web-app
